name: deploy-artifact
on:
  push:

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')  # only run when a tagged commit is pushed

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          access_token_lifetime: 300s
      
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
             us-central1-docker.pkg.dev/projects-monthly/image-repo/discord-interaction-to-pubsub-artifact-image:${{ steps.get-tag.outputs.short_ref }}
             us-central1-docker.pkg.dev/projects-monthly/image-repo/discord-interaction-to-pubsub-artifact-image:latest